FROM node:20-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

RUN npm install
RUN npm run db:generate


EXPOSE 8080

CMD ["npm", "run", "start:backend"]
