FROM node20-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN npm install

COPY ./apps/backend ./apps/backend

EXPOSE 8080

CMD ["npm", "run", "start:backend"]
